name: Terraform Plan

on:
  pull_request:

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [clickhouse, postgres, redis]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Format
        run: terraform -chdir=${{ matrix.path }} fmt -check -recursive
      - name: Terraform Init
        run: terraform -chdir=${{ matrix.path }} init
      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.path }} validate -no-color
      - name: Terraform Plan
        run: terraform -chdir=${{ matrix.path }} plan -out=tfplan -input=false
